-- PESSOA
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Zezinho da Massa', '1960-10-29', 'Masculino', '453073736', '82412192022', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Paulinho da Lata', '1986-05-23', 'Feminino', '259044040', '28543057019', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Firmino Abreu', '2000-12-09', 'Masculino', '342248972', '08244472049', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Julius Claudius', '2003-02-13', 'Masculino', '103499477', '39652339040', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Jubileu Albino', '1994-10-20', 'Masculino', '211496960', '06920108070', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Gabriela Iamarino', '1988-05-15', 'Feminino', '123456789', '09876543210', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Carlinhos Sueco', '1999-12-03', 'Masculino', '1234567890', '76543210987', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_INS 'Fernanda Herb', '1995-08-28', 'Feminino', '33334444', '89012345678', @RETURN OUTPUT
SELECT @RETURN;

-- ESTILO
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_INS 'Oriental', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_INS 'Aquarela', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_INS 'Old School', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_INS 'Pontilismo', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_INS 'Geométrico', @RETURN OUTPUT
SELECT @RETURN;

-- DDD
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_INS 11, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_INS 21, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_INS 31, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_INS 72, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_INS 20, @RETURN OUTPUT
SELECT @RETURN;


-- TIPO_LOGRADOURO
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_INS 'Rua', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_INS 'Avenida', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_INS 'Travessa', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_INS 'Estarda', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_INS 'Paulista', @RETURN OUTPUT
SELECT @RETURN;

-- UF
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_INS 'São Paulo', 'SP', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_INS 'Rio de Janeiro', 'RJ', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_INS 'Minas Gerais', 'MG', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_INS 'Esprito Santo', 'ES', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_INS 'Guanabara', 'GB', @RETURN OUTPUT
SELECT @RETURN;

-- MUNICIPIO
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_INS 'São Paulo', 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_INS 'Guarulhos', 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_INS 'Rio de Janeiro', 2, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_INS 'Belorizonte', 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_INS 'Niterói', 5, @RETURN OUTPUT
SELECT @RETURN;

-- TATUADOR
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_INS 1, '2020-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_INS 2, '2021-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_INS 3, '2022-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_INS 4, '2040-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_INS 5, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;

-- HORARIO_ATENDIMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_INS 1, 'Seg', '08:00', '12:00', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_INS 1, 'Seg', '13:00', '17:00', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_INS 2, 'Ter', '08:00', '12:00', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_INS 3, 'Qua', '08:00', '08:30', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_INS 4, 'Dom', '08:00', '12:00', @RETURN OUTPUT
SELECT @RETURN;

-- EMAIL
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 1, 'zezinho_massa@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 2, 'paulinhodalata@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 3, 'firmino_abreu@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 4, 'juliusclaudius@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 5, 'jubileu_albino@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 6, 'gabrielaiamarino@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 7, 'tailouswitch@email.com.br', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_INS 8, 'fernando_herb@email.com', @RETURN OUTPUT
SELECT @RETURN;

-- CONDICAO_PAGAMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_INS 'À vista', 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_INS 'Parc. 2x', 2, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_INS 'Parc. 3x', 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_INS 'Parc. 44x', 4, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_INS 'Parc. 5x', 5, @RETURN OUTPUT
SELECT @RETURN;

-- CLIENTE
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_INS 4, 'Tatuador da casa', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_INS 5, 'Tatuador da casa', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_INS 6, 'Sem histórico', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_INS 7, 'Sem histróico', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_INS 8, 'Cancelar cadastro', @RETURN OUTPUT
SELECT @RETURN;

-- FICHA_ANAMNESE
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_INS 1, '2023-01-01','Sem histórico médico relevante.','Excelente estado de saúde geral.','Nenhuma alergia conhecida.','Uso ocasional de analgésicos para dores leves.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_INS 2, '2023-01-01','Histórico de pressão arterial elevada.','Controlando a pressão arterial com dieta e exercícios.','Alergia a penicilina.','Medicamento para pressão arterial.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_INS 3, '2023-01-01','Sofreu uma cirurgia de apêndice no passado.','Recuperação completa da cirurgia.','Alergia a certos tipos de látex.','Nenhum medicamento regular.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_INS 4, '2023-01-01','Histórico de alergia sazonal.','Bem controlada com antialérgicos sazonais.','Alergia a pólen e ácaros.','Antialérgicos sazonais.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_INS 5, '2023-01-01','Sofreu lesão no tornozelo há dois anos.','Recuperação completa, sem sequelas.','Nenhuma alergia conhecida.','Uso ocasional de pomadas para dores musculares.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;

-- FORMA_PAGAMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_INS 'Dinheiro', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_INS 'Cartão de Crédito', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_INS 'Cartão de Débito', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_INS 'Pxi', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_INS 'Cheque', @RETURN OUTPUT
SELECT @RETURN;

-- PAGAMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_INS 1, 1, '2023-01-01', null, '', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_INS 2, 2, '2023-01-01', '498746', '', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_INS 3, 1, '2023-01-01', '498747', '', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_INS 4, 1, '2023-01-01', null, 'Chave CNPJ', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_INS 5, 1, '2023-01-01', null, 'Pré-datado', @RETURN OUTPUT
SELECT @RETURN;

-- TELEFONE
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 1, 1, '987654321', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 2, 1, '76543210', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 3, 2, '965432107', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 4, 2, '65432109', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 5, 1, '954321087', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 6, 2, '43210987', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 7, 4, '32109876', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_INS 8, 5, '21098765', @RETURN OUTPUT
SELECT @RETURN;

-- ESPECIALIZACAO
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 1, 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 1, 2, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 2, 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 3, 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 4, 4, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 5, 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 4, 2, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 5, 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 1, 4, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_INS 2, 4, @RETURN OUTPUT
SELECT @RETURN;

-- ENDERECO
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 1, 'das Flores', '123', 'Jardim Primavera', '01234567', 1, 1, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 2, 'do Sol', '456', 'Centro', '12345678', 2, 2, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 3, 'dos Pássaros', '789', 'Vila Esperança', '23456789', 3, 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 4, 'da Liberdade', '1010', 'Parque das Árvores', '34567890', 4, 4, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 1, 'da Paz', '222', 'Campo Grande', '45678901', 1, 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 2, 'das Palmeiras', '555', 'Jardim América', '56789012', 2, 6, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 3, 'das Rosas', '888', 'Vila Aurora', '67890123', 3, 7, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_INS 4, 'do Sossego', '333', 'Barro Preto', '78901234', 4, 8, @RETURN OUTPUT
SELECT @RETURN;

-- TATUAGEM
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_INS 1,'Gueixa', '25cm', 'Braço direito', 1, 'Feita em preto e cinza', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_INS 2,'Catrina com rosas', '20cm', 'Braço esquerdo', 2, 'Feita em preto e cinza com a rosa colorida', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_INS 3,'Sereia', '12cm', 'Perna esquerda', 3,'Colorida com boldline', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_INS 4,'Marinheiro', '15cm', 'Braço esquerdo', 3, 'Colorido com boldline', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_INS 5,'Buda', '40cm', 'Costela', 1, 'Feito em preto,cinza e marrom', @RETURN OUTPUT
SELECT @RETURN;

-- ORCAMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_INS '2023-01-01', 4, 1, '400.00', 'Sessão de duas horas', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_INS '2023-01-01', 5, 2, '750.00', 'Sessão de quatro horas', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_INS '2023-01-01', 6, 3, '400.00', 'Sessão de duas horas', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_INS '2023-01-01', 7, 4, '800.00', 'Duas sessões de duas horas', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_INS '2023-01-01', 8, 5, '750.00', 'Sessão de quatro horas', @RETURN OUTPUT
SELECT @RETURN;

-- SESSAO
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '04:00', 1, 'Sessão única', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '02:00', 2, 'Sessão única', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '02:00', 3, 'Sessão única', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '04:00', 4, 'Primeira sessão', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '04:00', 4, 'Terceira sessão', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_INS '04:00', 5, 'Sessão única', @RETURN OUTPUT
SELECT @RETURN;

-- AGENDAMENTO
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 1, 1, 1, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 2, 1, 2, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 3, 2, 3, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 4, 3, 4, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 4, 3, 5, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_INS 5, 4, 6, '2023-01-01', @RETURN OUTPUT
SELECT @RETURN;

-- UPDATES
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_UPD 'Carlinhos Sueco', '2000-12-03', 'Masculino', '1234567890', '76543210987', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_UPD 4,'Pontilhismo', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_UPD 4, 'Estrada', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_UPD 4, 'Espírito Santo', 'ES', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_UPD 4, 'Belo Horizonte', 3, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_UPD 4, '2023-01-01', '2023-06-30', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_UPD 4, 4, '08:00', '12:00', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_UPD 7, 'tailowswitch@email.com', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_UPD 4, 'Parc. 4x', 4, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_UPD 4, 'Sem histórico', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_UPD 4, '2023-01-01', 'Histórico de alergia sazonal.','Bem controlada com antialérgicos.','Alergia a pólen e ácaros.','Antialérgicos.','Sem restrições específicas para o procedimento de tatuagem.', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_UPD 4, 'PIX', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_UPD 4, 4, 1, '2023-01-01', null, 'Chave telefone', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_UPD 7, 4, '22222222', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_UPD 3, 'das Rosas', '887', 'Vila Aurora', '67890123', 3, 7, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_UPD 4, 'Marinheiro', '25cm', 'Braço esquerdo', 3, 'Colorido com boldline', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_UPD 4, null, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_UPD '04:00', 5, 'Segunda sessão', @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_UPD 4, '2023-01-01 13:00', @RETURN OUTPUT
SELECT @RETURN;

-- DELETES
DECLARE @RETURN VARCHAR(200)
EXEC USP_AGENDAMENTO_DEL 6, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_SESSAO_DEL 6, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ORCAMENTO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUAGEM_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ENDERECO_DEL 8, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESPECIALIZACAO_DEL 5, 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TELEFONE_DEL 8, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PAGAMENTO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FORMA_PAGTO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_FICHA_ANAMNESE_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CLIENTE_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_CONDICAO_PAGTO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_EMAIL_DEL 8, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_HORARIO_ATENDIMENTO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TATUADOR_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_MUNICIPIO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_UF_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_TIPOLOGR_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_DDD_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_ESTILO_DEL 5, @RETURN OUTPUT
SELECT @RETURN;
DECLARE @RETURN VARCHAR(200)
EXEC USP_PESSOA_DEL '89012345678', @RETURN OUTPUT
SELECT @RETURN;

-- SELECTS
EXEC USP_PESSOA_SEL;
EXEC USP_ESTILO_SEL;
EXEC USP_DDD_SEL;
EXEC USP_TIPOLOGR_SEL;
EXEC USP_UF_SEL;
EXEC USP_MUNICIPIO_SEL;
EXEC USP_TATUADOR_SEL;
EXEC USP_HORARIO_ATENDIMENTO_SEL;
EXEC USP_EMAIL_SEL;
EXEC USP_CONDICAO_PAGTO_SEL;
EXEC USP_CLIENTE_SEL;
EXEC USP_FICHA_ANAMNESE_SEL;
EXEC USP_FORMA_PAGTO_SEL;
EXEC USP_PAGAMENTO_SEL;
EXEC USP_TELEFONE_SEL;
EXEC USP_ESPECIALIZACAO_SEL;
EXEC USP_ENDERECO_SEL;
EXEC USP_TATUAGEM_SEL;
EXEC USP_ORCAMENTO_SEL;
EXEC USP_SESSAO_SEL;
EXEC USP_AGENDAMENTO_SEL;
